### ISSUE TITLE
Can't add server

### ISSUE THREAD

**Issue by natpavin** [ezaquarii/openvpn-at-home#2]
After runserver I can't add openvpn server to dashboard & It show message at below
"POST /api/openvpn/servers/ HTTP/1.1" 400 36

![screen shot 2561-02-26 at 12 48 18 pm](https://user-images.githubusercontent.com/13495978/36655122-621a6724-1af3-11e8-8b71-98662ee7a6dd.png)

OPENVPN Server IP : 10.211.55.15
Openvpen At Home IP : 10.211.55.15:8001

I have check about message log in CentOS and not found the error.

**Comment by ezaquarii** [comment]
Have you deployed all dependencies using `make devel`?

**Comment by natpavin** [comment]
Yes, i have deploy as make devel.

**Comment by ezaquarii** [comment]
Ok,  I'll take a look at this. Bear with me please.

**Comment by ezaquarii** [comment]
What is your timezone btw?

**Comment by natpavin** [comment]
GMT +7 Bangkok/Jakatar

**Comment by mrlexley** [comment]
In my case it was a problem with the GUI. Directly access the API worked fine. It looks like there is a CSS bug in the frontend, where the serverform disapears on the top of the screen. In the debugging screen you get a reply servername required. The browser I used was google chrome.

**Comment by ezaquarii** [comment]
@mrlexley There is currently an artificial limitation to 1 server. That is because I'm running only 1 server for my home installation and adding more would create more UX complexity. Please see the README for rationale.

Would you like to be able to manage more than 1 server? I could add it. It's just that I didn't need it.

**Comment by ezaquarii** [comment]
@mrlexley There is currently an artificial limitation to 1 server. That is because I'm running only 1 server for my home installation and adding more would create more UX complexity. Please see the README for rationale.

Would you like to be able to manage more than 1 server? I could add it. It's just that I didn't need it.

**Comment by mrlexley** [comment]
![2018-02-28 12_13_18-openvpn home - development](https://user-images.githubusercontent.com/19434518/36784999-a6a9e88a-1c81-11e8-9d1f-6143eda69bdb.png)
![2018-02-28 12_13_34-openvpn home - development](https://user-images.githubusercontent.com/19434518/36785005-ab361f4a-1c81-11e8-984d-ed37580e6b0d.png)
Look at my screenshots. When you add a server or client a small part of top of the form disappearing. Because of the inline CSS: margin-top:  -103px. For the client this is not a problem. But adding a server it is a problem. Because the inputfield "VPN Server Name" is falling of the screen.

**Comment by ezaquarii** [comment]
@mrlexley There is currently an artificial limitation to 1 server. That is because I'm running only 1 server for my home installation and adding more would create more UX complexity. Please see the README for rationale.

Would you like to be able to manage more than 1 server? I could add it. It's just that I didn't need it.

**Comment by ezaquarii** [comment]
Ok, I see. This is a bug. I see 2 options:
1) you create a PR  with a bugfix
2) we wait until I have time to fix it :)

**Comment by mrlexley** [comment]
I can't find where the top margin is initiated. There also seems to be a problem with required browser history in the statusbar. That's why the debug window/statusbar isn't loading.

**Comment by mrlexley** [comment]
The problem is in modal.js:
      if (dimmer) {
        mountNode.classList.add('dimmable');
        mountNode.classList.add('dimmed');

        if (dimmer === 'blurring') {
          mountNode.classList.add('blurring');
        }
      }

      if (_this.ref) {
        var _this$ref$getBounding = _this.ref.getBoundingClientRect(),
            height = _this$ref$getBounding.height;

        var marginTop = -Math.round(height / 2); <<<<<<<<<<<<<
        var scrolling = height >= window.innerHeight;

        var newState = {};

**Comment by ezaquarii** [comment]
Well, this is transpiled code. The bug must be somewhere in SemanticUI React components. I'll try to update SemanticUI to see if that fixes the problem.

**Comment by mrlexley** [comment]
I already tried. But that doesn't work.

**Comment by ezaquarii** [comment]
Ok, I found a quick workaround. If you zoom-in (250%), the dialog renders correctly in the middle of the screen. Apparently it has something to do with media queries. I'll continue my investigation.

**Comment by ezaquarii** [comment]
Adding style="display: flex !important;" in Chrome dev tools to the enclosing div fixes the issue, but I'm not sure why it doesn't work out of the box.

**Comment by ezaquarii** [comment]
This is the invalid dialog position demo:
![dialog-position](https://user-images.githubusercontent.com/1426823/36864917-fe176a0c-1d85-11e8-9f79-18e6d04abc37.png)

**Comment by mrlexley** [comment]
Yes, it is. Removing the style attribute fixes it. But I don't know why it happens. Adding a wrapper around it will also fix it.

**Comment by ezaquarii** [comment]
I asked reddit community for help. I hope somebody will have some idea.

**Comment by mrlexley** [comment]
Can you link the thread?

**Comment by ezaquarii** [comment]
https://www.reddit.com/r/reactjs/comments/817yot/help_needed_openvpnhome_issue_with_semanticui/

**Comment by ezaquarii** [comment]
@mrlexley  What kind of wrapper did you make to fix it?

**Comment by ezaquarii** [comment]
It turned out that npm installed a newer version of Semantic-UI that didn't work. Pinning the version fixed the problem.
